# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
  url: <%= ENV["DATABASE_URL"] %>
  prepared_statements: <%= ENV.fetch("PREPARED_STATEMENTS", "false") == "true" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
