# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL", "") %>
  pool: 10
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
